"use client";
import {useState} from "react";
import {addDoc,collection,Timestamp} from "firebase/firestore";
import {db} from "../../lib/firebase";
import {CalendarCheck,Clock3,MapPin,ShieldCheck,CheckCircle2,ArrowLeft} from "lucide-react";

const LOCATIONS=[
 {id:"ADMIN",name:"Main Admin Office"},{id:"I",name:"Warehouse I"},{id:"J",name:"Warehouse J"},{id:"K",name:"Warehouse K"},{id:"L",name:"Warehouse L"},{id:"O",name:"Warehouse O"},{id:"P",name:"Warehouse P"},{id:"Q",name:"Warehouse Q"},{id:"R",name:"Warehouse R"},{id:"S",name:"Warehouse S"},{id:"T",name:"Warehouse T"},{id:"H14-MHE",name:"H14 (MHE)"}
];
const PURPOSES=["Meeting","Visitor","Official","Interview","Delivery","Others"];
const today=()=>new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Kolkata"});
const refNo=()=>{const d=today().replaceAll("-","");return "APT-"+d+"-"+String(Date.now()).slice(-6)};

export default function AppointmentBooking(){
 const [f,setF]=useState<any>({locationId:"",appointmentDate:today(),appointmentTime:"10:00",visitorName:"",company:"",mobile:"",email:"",hostName:"",purpose:"Meeting",remarks:""}),[saving,setSaving]=useState(false),[done,setDone]=useState<any>(null),[error,setError]=useState("");
 const u=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
 const submit=async(e:any)=>{e.preventDefault();setSaving(true);setError("");try{
   if(!f.locationId)throw new Error("Select the location you are visiting.");
   const selected=LOCATIONS.find(x=>x.id===f.locationId); if(!selected)throw new Error("Invalid location.");
   if(f.appointmentDate<today())throw new Error("Appointment date cannot be in the past.");
   const appointmentNo=refNo();
   const ref=await addDoc(collection(db,"visitorAppointments"),{appointmentNo,locationId:f.locationId,locationName:selected.name,appointmentDate:f.appointmentDate,appointmentTime:f.appointmentTime,visitorName:f.visitorName.trim(),company:f.company.trim(),mobile:f.mobile.trim(),email:f.email.trim(),hostName:f.hostName.trim(),purpose:f.purpose,remarks:f.remarks.trim(),status:"PENDING",createdAt:Timestamp.now()});
   setDone({id:ref.id,appointmentNo,locationName:selected.name,date:f.appointmentDate,time:f.appointmentTime,visitorName:f.visitorName}); 
 }catch(err:any){setError(err.message||"Unable to submit appointment. Please try again.");}finally{setSaving(false)}};
 if(done){
  return <main className="bookingPage"><div className="bookingShell bookingSuccess"><div className="bookingBrand"><div className="bookingLogo">S</div><div><b>SAIDHARA NDC</b><span>VISITOR APPOINTMENTS</span></div></div><div className="successIcon"><CheckCircle2 size={34}/></div><span className="bookingEyebrow">REQUEST RECEIVED</span><h1>Appointment request submitted.</h1><p>Your request is now with the security desk for review. Keep this reference number with you.</p><div className="appointmentTicket"><div><small>APPOINTMENT REFERENCE</small><strong>{done.appointmentNo}</strong></div><div><small>LOCATION</small><b>{done.locationName}</b></div><div><small>VISITOR</small><b>{done.visitorName}</b></div><div><small>DATE &amp; TIME</small><b>{done.date} · {done.time} IST</b></div><div className="ticketStatus">PENDING APPROVAL</div></div><button type="button" className="bookingSecondary" onClick={()=>setDone(null)}><ArrowLeft size={16}/> Book another appointment</button></div></main>;
 }
 return <main className="bookingPage"><div className="bookingShell"><div className="bookingTop"><div className="bookingBrand"><div className="bookingLogo">S</div><div><b>SAIDHARA NDC</b><span>VISITOR APPOINTMENTS</span></div></div><div className="bookingSecure"><ShieldCheck size={16}/> Secure booking</div></div><div className="bookingHero"><div><span className="bookingEyebrow">VISITOR ACCESS</span><h1>Book your visit.</h1><p>Submit an appointment request for the Saidhara NDC location you plan to visit. No login is required.</p></div><div className="bookingHeroIcon"><CalendarCheck size={34}/></div></div><form onSubmit={submit} className="bookingForm"><div className="bookingSection"><div className="bookingSectionTitle"><MapPin/><div><b>Where are you visiting?</b><span>Select the exact office or warehouse.</span></div></div><label>Location *<select value={f.locationId} onChange={e=>u("locationId",e.target.value)} required><option value="">Select location</option>{LOCATIONS.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></div><div className="bookingGrid"><label>Appointment date *<input type="date" min={today()} value={f.appointmentDate} onChange={e=>u("appointmentDate",e.target.value)} required/></label><label>Appointment time *<input type="time" value={f.appointmentTime} onChange={e=>u("appointmentTime",e.target.value)} required/></label><label>Visitor name *<input value={f.visitorName} onChange={e=>u("visitorName",e.target.value)} required placeholder="Full name"/></label><label>Company / organisation<input value={f.company} onChange={e=>u("company",e.target.value)} placeholder="Company name"/></label><label>Mobile number *<input inputMode="tel" value={f.mobile} onChange={e=>u("mobile",e.target.value)} required placeholder="10-digit mobile number"/></label><label>Email address<input type="email" value={f.email} onChange={e=>u("email",e.target.value)} placeholder="Optional"/></label><label>Person to meet *<input value={f.hostName} onChange={e=>u("hostName",e.target.value)} required placeholder="e.g. Sohail Kachhi"/></label><label>Purpose<select value={f.purpose} onChange={e=>u("purpose",e.target.value)}>{PURPOSES.map(x=><option key={x}>{x}</option>)}</select></label><label className="bookingFull">Additional information<textarea rows={3} value={f.remarks} onChange={e=>u("remarks",e.target.value)} placeholder="Anything the security desk should know?"/></label></div>{error&&<div className="bookingError">{error}</div>}<div className="bookingSubmit"><div><Clock3 size={16}/><span>Arrive within the scheduled window after approval.</span></div><button className="bookingPrimary" disabled={saving}>{saving?"Submitting…":"Request appointment"}<CalendarCheck size={17}/></button></div></form><div className="bookingFoot">Your appointment remains <b>Pending Approval</b> until the destination security desk reviews it. Please carry a valid ID when you visit.</div></div></main>;
}
