'use client';
import {useEffect,useRef,useState} from "react";
import {auth,db,storage} from "../lib/firebase";
import {onAuthStateChanged,signInWithEmailAndPassword} from "firebase/auth";
import {doc,getDoc,collection,query,where,onSnapshot,addDoc,updateDoc,serverTimestamp,setDoc} from "firebase/firestore";
import {ref,uploadString,getDownloadURL} from "firebase/storage";
import {LayoutDashboard,Users,PackageCheck,Ticket,BarChart3,Settings,LogOut,Plus,Search,Camera,CheckCircle2,Clock3,ShieldCheck,X,Menu,MapPin,RefreshCw} from "lucide-react";

type Profile={uid:string;name:string;email:string;role:"admin"|"security";locationId:string;active:boolean};
type Location={id:string;name:string};
const LOCATIONS:Location[]=[
{id:"ADMIN",name:"Main Admin Office"},{id:"I",name:"Warehouse I"},{id:"J",name:"Warehouse J"},{id:"K",name:"Warehouse K"},{id:"L",name:"Warehouse L"},{id:"O",name:"Warehouse O"},{id:"P",name:"Warehouse P"},{id:"Q",name:"Warehouse Q"},{id:"R",name:"Warehouse R"},{id:"S",name:"Warehouse S"},{id:"T",name:"Warehouse T"},{id:"H14-MHE",name:"H14 (MHE)"}];
const purposes=["Meeting","Visitor","Official","Others"];
const today=()=>new Date().toISOString().slice(0,10);
const locName=(id:string)=>LOCATIONS.find(x=>x.id===id)?.name||id;
const fmt=(v:any)=>v?.toDate?v.toDate().toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):v?new Date(v).toLocaleString("en-IN",{dateStyle:"medium",timeStyle:"short"}):"—";

export default function Home(){
 const [profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){setProfile(null);setLoading(false);return}const s=await getDoc(doc(db,"users",u.uid));if(s.exists())setProfile({uid:u.uid,...s.data()} as Profile);else setError("Account profile is not configured. Ask the administrator.");setLoading(false)}),[]);
 if(loading)return <div className="splash"><div className="brandMark">S</div><h2>SAIDHARA NDC</h2><p>Visitor & Asset Management</p></div>;
 if(!profile)return <Login email={email} password={password} setEmail={setEmail} setPassword={setPassword} error={error} setError={setError}/>;
 return <Portal profile={profile}/>;
}

function Login(p:any){
 const submit=async(e:any)=>{e.preventDefault();p.setError("");try{await signInWithEmailAndPassword(auth,p.email,p.password)}catch(e:any){p.setError(e.code==="auth/invalid-credential"?"Invalid email or password.":"Unable to sign in. Check Firebase Authentication.")}};
 return <main className="login"><div className="loginCard"><div className="logoCircle">S</div><div className="eyebrow">SAIDHARA NDC</div><h1>Secure operations portal</h1><p className="muted">Manage visitors, assets and gate passes for your assigned location.</p><form onSubmit={submit}><label>Email<input type="email" value={p.email} onChange={e=>p.setEmail(e.target.value)} placeholder="security@vms.com" required/></label><label>Password<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} placeholder="••••••••" required/></label>{p.error&&<div className="error">{p.error}</div>}<button className="primary wide">Sign in securely</button></form><div className="loginFoot"><ShieldCheck size={16}/> Location-based access control enabled</div></div></main>;
}

function Portal({profile}:{profile:Profile}){
 const [tab,setTab]=useState("dashboard"),[mobile,setMobile]=useState(false),[refresh,setRefresh]=useState(0);
 const allowed=profile.role==="admin"?LOCATIONS:LOCATIONS.filter(x=>x.id===profile.locationId);
 const items:any[]=[["dashboard","Dashboard",LayoutDashboard],["visitors","Visitors",Users],["assets","Assets",PackageCheck],["gatepasses","Gate Passes",Ticket],["analytics","Analytics",BarChart3],...(profile.role==="admin"?[["settings","Settings",Settings]]:[])];
 return <div className="app"><aside className={mobile?"side open":"side"}><div className="sideBrand"><div className="logoCircle small">S</div><div><b>SAIDHARA</b><span>NDC OPERATIONS</span></div></div><div className="locationPill"><MapPin size={15}/>{profile.role==="admin"?"All locations":locName(profile.locationId)}</div><nav>{items.map(([id,label,Icon])=><button className={tab===id?"nav active":"nav"} onClick={()=>{setTab(id);setMobile(false)}} key={id}><Icon size={19}/><span>{label}</span></button>)}</nav><div className="sideBottom"><div className="profileMini"><div className="avatar">{profile.name?.slice(0,1)||"S"}</div><div><b>{profile.name}</b><span>{profile.role==="admin"?"Administrator":"Desk Security"}</span></div></div><button className="nav logout" onClick={()=>import("firebase/auth").then(x=>x.signOut(auth))}><LogOut size={18}/> Sign out</button></div></aside><section className="main"><header><div className="headLeft"><button className="mobileMenu" onClick={()=>setMobile(!mobile)}><Menu/></button><div><span className="crumb">NDC / {profile.role==="admin"?"CONTROL CENTER":locName(profile.locationId).toUpperCase()}</span><h2>{tab==="dashboard"?"Operations Dashboard":tab[0].toUpperCase()+tab.slice(1)}</h2></div></div><button className="iconBtn" title="Refresh" onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={18}/></button></header><div className="content"><Page tab={tab} profile={profile} allowed={allowed} refresh={refresh}/></div></section></div>;
}

function Page({tab,profile,allowed,refresh}:{tab:string;profile:Profile;allowed:Location[];refresh:number}){
 if(tab==="dashboard")return <Dashboard profile={profile}/>;
 if(tab==="visitors")return <Visitors profile={profile} allowed={allowed} refresh={refresh}/>;
 if(tab==="assets")return <Assets profile={profile} refresh={refresh}/>;
 if(tab==="gatepasses")return <GatePasses profile={profile} refresh={refresh}/>;
 if(tab==="analytics")return <Analytics profile={profile} allowed={allowed}/>;
 return <SettingsPage/>;
}

function Stat({label,value,icon}:any){return <div className="stat"><div className="statIcon">{icon}</div><div><span>{label}</span><strong>{value}</strong></div></div>}

function Dashboard({profile}:{profile:Profile}){
 const [stats,setStats]=useState({today:0,inside:0,assets:0,passes:0});
 useEffect(()=>{const ids=profile.role==="admin"?LOCATIONS.map(x=>x.id):[profile.locationId];const visitorToday:any={},visitorInside:any={},assets:any={},passes:any={};
 const apply=()=>setStats({today:Object.values(visitorToday).reduce((a:any,b:any)=>a+b,0),inside:Object.values(visitorInside).reduce((a:any,b:any)=>a+b,0),assets:Object.values(assets).reduce((a:any,b:any)=>a+b,0),passes:Object.values(passes).reduce((a:any,b:any)=>a+b,0)});
 const us=ids.map(id=>onSnapshot(query(collection(db,"visitors"),where("locationId","==",id)),s=>{visitorToday[id]=s.docs.filter(d=>d.data().entryDate===today()).length;visitorInside[id]=s.docs.filter(d=>!d.data().checkOutAt).length;apply()}));
 const as=ids.map(id=>onSnapshot(query(collection(db,"assets"),where("locationId","==",id)),s=>{assets[id]=s.size;apply()}));
 const gs=ids.map(id=>onSnapshot(query(collection(db,"gatePasses"),where("locationId","==",id)),s=>{passes[id]=s.size;apply()}));
 return()=>[...us,...as,...gs].forEach(u=>u())},[profile]);
 return <><div className="hero"><div><span className="eyebrow">GOOD DAY, {profile.name?.split(" ")[0]?.toUpperCase()}</span><h1>Keep the gate moving.</h1><p>Everything your front desk needs, in one secure workspace.</p></div><div className="heroBadge"><ShieldCheck/><span>Firebase secured</span></div></div><div className="stats"><Stat label="Visitors today" value={stats.today} icon={<Users/>}/><Stat label="Currently inside" value={stats.inside} icon={<Clock3/>}/><Stat label="Assets recorded" value={stats.assets} icon={<PackageCheck/>}/><Stat label="Gate passes" value={stats.passes} icon={<Ticket/>}/></div><div className="grid2"><div className="panel"><div className="panelHead"><div><b>Front desk workflow</b><span>Fast actions for daily operations</span></div></div><div className="quick"><Quick title="Visitors" text="Register and check out guests" icon={<Users/>}/><Quick title="Assets" text="Returnable and non-returnable" icon={<PackageCheck/>}/><Quick title="Gate passes" text="Controlled material movement" icon={<Ticket/>}/></div></div><div className="panel securityPanel"><ShieldCheck size={28}/><b>Access boundary</b><p>{profile.role==="admin"?"You have administrator visibility across every NDC location.":"You are restricted to "+locName(profile.locationId)+". Other locations are blocked by Firestore rules."}</p></div></div></>;
}
function Quick({title,text,icon}:any){return <div className="quickBtn"><span>{icon}</span><b>{title}</b><small>{text}</small><Plus size={17}/></div>}

function Visitors({profile,allowed,refresh}:{profile:Profile;allowed:Location[];refresh:number}){
 const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false),[filter,setFilter]=useState(""),[location,setLocation]=useState(profile.role==="admin"?"ALL":profile.locationId);
 useEffect(()=>{const ids=profile.role==="admin"?(location==="ALL"?LOCATIONS.map(x=>x.id):[location]):[profile.locationId];const us=ids.map(id=>onSnapshot(query(collection(db,"visitors"),where("locationId","==",id)),s=>setRows(old=>[...old.filter(x=>x.locationId!==id),...s.docs.map(d=>({id:d.id,...d.data()}))])));return()=>us.forEach(x=>x())},[profile,location,refresh]);
 const shown=rows.filter(r=>[r.name,r.company,r.mobile,r.serialNo].join(" ").toLowerCase().includes(filter.toLowerCase()));
 return <><Toolbar title="Visitor register" subtitle="Check guests in and out with a complete audit trail." onAdd={()=>setOpen(true)} addText="New visitor" search={filter} setSearch={setFilter}>{profile.role==="admin"&&<select value={location} onChange={e=>{setRows([]);setLocation(e.target.value)}}><option value="ALL">All locations</option>{allowed.filter(x=>x.id!=="ADMIN").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>}</Toolbar><div className="tablePanel"><div className="tableScroll"><table><thead><tr><th>Serial</th><th>Visitor</th><th>Company</th><th>Whom to meet</th><th>Check in</th><th>Status</th><th>Location</th><th></th></tr></thead><tbody>{shown.map(r=><VisitorRow key={r.id} r={r}/>)}</tbody></table>{!shown.length&&<Empty text="No visitor records found."/>}</div></div>{open&&<VisitorModal profile={profile} onClose={()=>setOpen(false)}/>}</>;
}
function VisitorRow({r}:{r:any}){const checkout=async()=>{await updateDoc(doc(db,"visitors",r.id),{checkOutAt:serverTimestamp(),updatedAt:serverTimestamp()})};return <tr><td><b>{r.serialNo}</b><small>{r.entryDate}</small></td><td><b>{r.name}</b><small>{r.mobile}</small></td><td>{r.company||"—"}</td><td>{r.whomToMeet||"—"}<small>{r.purpose}</small></td><td>{fmt(r.checkInAt)}</td><td>{r.checkOutAt?<span className="badge neutral">Checked out</span>:<span className="badge green">Inside</span>}</td><td>{locName(r.locationId)}</td><td>{!r.checkOutAt&&<button className="checkout" onClick={checkout}><CheckCircle2 size={15}/> Check out</button>}</td></tr>}

function VisitorModal({profile,onClose}:{profile:Profile;onClose:()=>void}){
 const [f,setF]=useState<any>({serialNo:"",name:"",company:"",mobile:"",whomToMeet:"",purpose:"Meeting",remarks:"",locationId:profile.role==="admin"?"I":profile.locationId,photo:""}),[saving,setSaving]=useState(false),[camera,setCamera]=useState(false);
 const video=useRef<HTMLVideoElement>(null);const update=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
 // Visitor form state updater
 const openCam=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:true});if(video.current){video.current.srcObject=s;await video.current.play()}setCamera(true)}catch{alert("Camera access was not granted. You can continue without a photo.")}};
 const snap=()=>{const c=document.createElement("canvas");c.width=video.current!.videoWidth;c.height=video.current!.videoHeight;c.getContext("2d")!.drawImage(video.current!,0,0);update("photo",c.toDataURL("image/jpeg",.72));(video.current!.srcObject as MediaStream)?.getTracks().forEach(t=>t.stop());setCamera(false)};
 const save=async(e:any)=>{e.preventDefault();setSaving(true);try{let photoUrl="";if(f.photo){const rr=ref(storage,"visitorPhotos/"+f.locationId+"/"+crypto.randomUUID()+".jpg");await uploadString(rr,f.photo,"data_url");photoUrl=await getDownloadURL(rr)}await addDoc(collection(db,"visitors"),{serialNo:f.serialNo||("V-"+Date.now()),date:today(),entryDate:today(),name:f.name,company:f.company,mobile:f.mobile,whomToMeet:f.whomToMeet,purpose:f.purpose,checkInAt:serverTimestamp(),checkOutAt:null,photoUrl,remarks:f.remarks,locationId:f.locationId,securityId:profile.uid,securityName:profile.name,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});onClose()}catch(err:any){alert(err.message||"Could not save visitor.")}finally{setSaving(false)}};
 return <Modal title="Register new visitor" onClose={onClose}><form onSubmit={save} className="formGrid"><Field label="Serial number"><input value={f.serialNo} onChange={e=>update("serialNo",e.target.value)} placeholder="Auto if blank"/></Field><Field label="Entry date"><input value={today()} readOnly/></Field><Field label="Visitor name" required><input value={f.name} onChange={e=>update("name",e.target.value)} required/></Field><Field label="Company name"><input value={f.company} onChange={e=>update("company",e.target.value)}/></Field><Field label="Mobile number" required><input inputMode="tel" value={f.mobile} onChange={e=>update("mobile",e.target.value)} required/></Field><Field label="Whom to meet"><input value={f.whomToMeet} onChange={e=>update("whomToMeet",e.target.value)}/></Field><Field label="Purpose"><select value={f.purpose} onChange={e=>update("purpose",e.target.value)}>{purposes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Desk security"><select value={profile.uid} disabled><option value={profile.uid}>{profile.name}</option></select></Field>{profile.role==="admin"&&<Field label="Location"><select value={f.locationId} onChange={e=>update("locationId",e.target.value)}>{LOCATIONS.filter(x=>x.id!=="ADMIN").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}<div className="full photoBox">{camera?<><video ref={video} muted/><button type="button" className="primary" onClick={snap}><Camera size={16}/> Capture photo</button></>:<><div className="photoPreview">{f.photo?<img src={f.photo}/>:<Camera size={24}/>}</div><button type="button" className="secondary" onClick={openCam}><Camera size={16}/> {f.photo?"Retake":"Capture"} photo <small>optional</small></button></>}</div><Field label="Remarks" full><textarea rows={3} value={f.remarks} onChange={e=>update("remarks",e.target.value)}/></Field><div className="modalActions full"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Check in visitor"}</button></div></form></Modal>;
}

function Assets({profile,refresh}:{profile:Profile;refresh:number}){
 const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>{const ids=profile.role==="admin"?LOCATIONS.map(x=>x.id):[profile.locationId];const us=ids.map(id=>onSnapshot(query(collection(db,"assets"),where("locationId","==",id)),s=>setRows(old=>[...old.filter(x=>x.locationId!==id),...s.docs.map(d=>({id:d.id,...d.data()}))])));return()=>us.forEach(x=>x())},[profile,refresh]);
 return <><Toolbar title="Asset register" subtitle="Track company assets, ownership, return status and optional gate passes." onAdd={()=>setOpen(true)} addText="Record asset"/><div className="tablePanel"><div className="tableScroll"><table><thead><tr><th>Asset number</th><th>Asset details</th><th>Issued to</th><th>Issued by</th><th>Type</th><th>Gate pass</th><th>Location</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.assetNumber}</b><small>{fmt(r.issueDate)}</small></td><td>{r.assetDetails}</td><td>{r.issuedTo}</td><td>{r.issuedBy}</td><td><span className="badge neutral">{r.type}</span></td><td>{r.gatePassRequired?"Required":"—"}</td><td>{locName(r.locationId)}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No assets recorded yet."/>}</div></div>{open&&<AssetModal profile={profile} onClose={()=>setOpen(false)}/>}</>;
}
function AssetModal({profile,onClose}:{profile:Profile;onClose:()=>void}){
 const [f,setF]=useState<any>({assetNumber:"",assetDetails:"",issuedTo:"",issuedBy:profile.name,type:"RETURNABLE",gatePassRequired:false,locationId:profile.role==="admin"?"I":profile.locationId,remarks:""}),[saving,setSaving]=useState(false);
 const u=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));const save=async(e:any)=>{e.preventDefault();setSaving(true);try{const assetRef=await addDoc(collection(db,"assets"),{...f,issueDate:serverTimestamp(),status:f.type==="RETURNABLE"?"ISSUED":"DISPATCHED",createdAt:serverTimestamp(),updatedAt:serverTimestamp()});if(f.gatePassRequired){await addDoc(collection(db,"gatePasses"),{passNo:"GP-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-6),passType:"ASSET / MATERIAL",holder:f.issuedTo,purpose:"Asset movement: "+f.assetDetails,assetId:assetRef.id,locationId:f.locationId,status:"ACTIVE",createdBy:profile.uid,createdByName:profile.name,createdAt:serverTimestamp()})}onClose()}catch(err:any){alert(err.message)}finally{setSaving(false)}};
 return <Modal title="Record asset movement" onClose={onClose}><form onSubmit={save} className="formGrid"><Field label="Asset number" required><input value={f.assetNumber} onChange={e=>u("assetNumber",e.target.value)} required placeholder="e.g. LAP-00124"/></Field><Field label="Asset type"><select value={f.type} onChange={e=>u("type",e.target.value)}><option>RETURNABLE</option><option>NON-RETURNABLE</option></select></Field><Field label="Asset details / what is issued" full required><textarea value={f.assetDetails} onChange={e=>u("assetDetails",e.target.value)} required placeholder="Laptop, charger, bag, tools…"/></Field><Field label="Issued to" required><input value={f.issuedTo} onChange={e=>u("issuedTo",e.target.value)} required/></Field><Field label="Issued by" required><input value={f.issuedBy} onChange={e=>u("issuedBy",e.target.value)} required/></Field>{profile.role==="admin"&&<Field label="Location"><select value={f.locationId} onChange={e=>u("locationId",e.target.value)}>{LOCATIONS.filter(x=>x.id!=="ADMIN").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}<label className="check"><input type="checkbox" checked={f.gatePassRequired} onChange={e=>u("gatePassRequired",e.target.checked)}/> Generate gate pass later / link this asset to a pass</label><Field label="Remarks" full><textarea value={f.remarks} onChange={e=>u("remarks",e.target.value)}/></Field><div className="modalActions full"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Saving…":"Save asset entry"}</button></div></form></Modal>;
}

function GatePasses({profile,refresh}:{profile:Profile;refresh:number}){
 const [rows,setRows]=useState<any[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>{const ids=profile.role==="admin"?LOCATIONS.map(x=>x.id):[profile.locationId];const us=ids.map(id=>onSnapshot(query(collection(db,"gatePasses"),where("locationId","==",id)),s=>setRows(old=>[...old.filter(x=>x.locationId!==id),...s.docs.map(d=>({id:d.id,...d.data()}))])));return()=>us.forEach(x=>x())},[profile,refresh]);
 return <><Toolbar title="Gate pass control" subtitle="Issue controlled passes for visitor or material movements." onAdd={()=>setOpen(true)} addText="Generate pass"/><div className="tablePanel"><div className="tableScroll"><table><thead><tr><th>Pass no.</th><th>Type</th><th>Holder / party</th><th>Purpose</th><th>Issued</th><th>Status</th><th>Location</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.passNo}</b></td><td><span className="badge neutral">{r.passType}</span></td><td>{r.holder}</td><td>{r.purpose}</td><td>{fmt(r.createdAt)}</td><td><span className="badge green">{r.status||"ACTIVE"}</span></td><td>{locName(r.locationId)}</td></tr>)}</tbody></table>{!rows.length&&<Empty text="No gate passes generated yet."/>}</div></div>{open&&<PassModal profile={profile} onClose={()=>setOpen(false)}/>}</>;
}
function PassModal({profile,onClose}:{profile:Profile;onClose:()=>void}){
 const [f,setF]=useState<any>({passType:"VISITOR",holder:"",purpose:"",locationId:profile.role==="admin"?"I":profile.locationId,validUntil:""});const u=(k:string,v:any)=>setF((x:any)=>({...x,[k]:v}));
 const save=async(e:any)=>{e.preventDefault();try{await addDoc(collection(db,"gatePasses"),{...f,passNo:"GP-"+new Date().getFullYear()+"-"+String(Date.now()).slice(-6),status:"ACTIVE",createdBy:profile.uid,createdByName:profile.name,createdAt:serverTimestamp()});onClose()}catch(err:any){alert((err as any).message)}};
 return <Modal title="Generate gate pass" onClose={onClose}><form onSubmit={save} className="formGrid"><Field label="Pass type"><select value={f.passType} onChange={e=>u("passType",e.target.value)}><option>VISITOR</option><option>ASSET / MATERIAL</option></select></Field><Field label="Holder / party" required><input value={f.holder} onChange={e=>u("holder",e.target.value)} required/></Field><Field label="Purpose" full required><input value={f.purpose} onChange={e=>u("purpose",e.target.value)} required/></Field><Field label="Valid until"><input type="datetime-local" value={f.validUntil} onChange={e=>u("validUntil",e.target.value)}/></Field>{profile.role==="admin"&&<Field label="Location"><select value={f.locationId} onChange={e=>u("locationId",e.target.value)}>{LOCATIONS.filter(x=>x.id!=="ADMIN").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}<div className="modalActions full"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary">Generate pass</button></div></form></Modal>;
}

function Analytics({profile,allowed}:{profile:Profile;allowed:Location[]}){
 const [rows,setRows]=useState<any[]>([]);useEffect(()=>{const ids=profile.role==="admin"?LOCATIONS.map(x=>x.id):[profile.locationId];const us=ids.map(id=>onSnapshot(query(collection(db,"visitors"),where("locationId","==",id)),s=>setRows(old=>[...old.filter(x=>x.locationId!==id),...s.docs.map(d=>d.data())])));return()=>us.forEach(x=>x())},[profile]);
 const byLoc=allowed.filter(x=>x.id!=="ADMIN").map(l=>({l,n:rows.filter(r=>r.locationId===l.id).length}));const max=Math.max(1,...byLoc.map(x=>x.n));
 return <><div className="hero compact"><div><span className="eyebrow">OPERATIONS INTELLIGENCE</span><h1>Analytics at a glance.</h1><p>Visitor activity and location distribution based on recorded entries.</p></div></div><div className="stats"><Stat label="Total visitors" value={rows.length} icon={<Users/>}/><Stat label="Checked in" value={rows.filter(r=>!r.checkOutAt).length} icon={<Clock3/>}/><Stat label="Checked out" value={rows.filter(r=>r.checkOutAt).length} icon={<CheckCircle2/>}/><Stat label="Active locations" value={byLoc.filter(x=>x.n>0).length} icon={<MapPin/>}/></div><div className="panel"><div className="panelHead"><div><b>Visitors by location</b><span>Admin sees the complete NDC footprint; security sees its assigned location.</span></div></div><div className="bars">{byLoc.map(x=><div className="barRow" key={x.l.id}><span>{x.l.name}</span><div><i style={{width:Math.min(100,Math.max(4,x.n/max*100))+"%"}}/></div><b>{x.n}</b></div>)}</div></div></>;
}

function SettingsPage(){
 const [users,setUsers]=useState<any[]>([]),[open,setOpen]=useState(false);
 useEffect(()=>onSnapshot(query(collection(db,"users"),where("role","==","security")),s=>setUsers(s.docs.map(d=>({id:d.id,...d.data()})))),[]);
 return <><Toolbar title="Security & locations" subtitle="Create location-bound desk security accounts and control access." onAdd={()=>setOpen(true)} addText="Add security"/><div className="settingsGrid">{LOCATIONS.map(l=><div className="locationCard" key={l.id}><div className="locIcon"><MapPin size={19}/></div><div><b>{l.name}</b><span>{users.filter(u=>u.locationId===l.id&&u.active!==false).length} active security account(s)</span></div><span className="dot"/></div>)}</div><div className="tablePanel"><div className="tableScroll"><table><thead><tr><th>Name</th><th>Email</th><th>Location</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b></td><td>{u.email}</td><td>{locName(u.locationId)}</td><td><span className="badge green">{u.active===false?"Disabled":"Active"}</span></td></tr>)}</tbody></table></div></div>{open&&<SecurityModal onClose={()=>setOpen(false)}/>}</>;
}

function SecurityModal({onClose}:{onClose:()=>void}){
 const [f,setF]=useState({name:"",email:"",password:"",locationId:"I"}),[saving,setSaving]=useState(false);const u=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
 const save=async(e:any)=>{e.preventDefault();setSaving(true);let secondary:any;try{const {initializeApp:ia,deleteApp}=await import("firebase/app");const {getAuth:ga,createUserWithEmailAndPassword:cw}=await import("firebase/auth");secondary=ia({apiKey:process.env.NEXT_PUBLIC_FIREBASE_API_KEY,authDomain:process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,projectId:process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,storageBucket:process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,messagingSenderId:process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,appId:process.env.NEXT_PUBLIC_FIREBASE_APP_ID},"security-creator");const cred=await cw(ga(secondary),f.email,f.password);await setDoc(doc(db,"users",cred.user.uid),{name:f.name,email:f.email,role:"security",locationId:f.locationId,active:true,createdAt:serverTimestamp()});const {deleteApp:da}=await import("firebase/app");await da(secondary);onClose()}catch(err:any){try{if(secondary){const {deleteApp}=await import("firebase/app");await deleteApp(secondary)}}catch{}alert(err.code==="auth/email-already-in-use"?"That email already exists.":"Could not create security account: "+err.message)}finally{setSaving(false)}};
 return <Modal title="Add desk security" onClose={onClose}><form onSubmit={save} className="formGrid"><Field label="Security name" required><input value={f.name} onChange={e=>u("name",e.target.value)} required/></Field><Field label="Login email" required><input type="email" value={f.email} onChange={e=>u("email",e.target.value)} required/></Field><Field label="Temporary password" required><input type="password" minLength={6} value={f.password} onChange={e=>u("password",e.target.value)} required/></Field><Field label="Assigned location" required><select value={f.locationId} onChange={e=>u("locationId",e.target.value)}>{LOCATIONS.filter(x=>x.id!=="ADMIN").map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><div className="notice full"><ShieldCheck size={17}/> This account can only access the selected location. Firestore rules enforce the same boundary.</div><div className="modalActions full"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={saving}>{saving?"Creating…":"Create security login"}</button></div></form></Modal>;
}

function Toolbar({title,subtitle,onAdd,addText,search,setSearch,children}:any){return <div className="toolbar"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="toolbarActions">{children}{setSearch&&<div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records…"/></div>}<button className="primary" onClick={onAdd}><Plus size={17}/>{addText}</button></div></div>}
function Modal({title,onClose,children}:any){return <div className="overlay"><div className="modal"><div className="modalHead"><div><span className="eyebrow">SAIDHARA NDC</span><h2>{title}</h2></div><button className="iconBtn" onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
function Field({label,children,full,required}:any){return <label className={full?"field full":"field"}><span>{label}{required&&" *"}</span>{children}</label>}
function Empty({text}:any){return <div className="empty"><Users size={24}/><b>{text}</b><span>New records will appear here automatically.</span></div>}
